# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eb1c458f6ba50a63f62395291f5ed9f8a46c185a55fa408571fef531838ee593ed482e0579ef1d85ff15e9bf0f7b12401acf4e22f3df02329fdf096d6d610e7

test:
  secret_key_base: ae8d709ff39bc6204934a791f23c4a4a494bc25d56e2dd78933dc30520e7fbcf9566fe5c658e6c3e74ef2220d8dcacaf973b01d2d9bae34699fe79048381aa2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
